# Basic Information 
title: Shuyi Yu
position: Ph.D. Candidate
affiliation: University of Chicago
subaffiliation: Political Science
affiliation_logo: ./assets/img/illinois.svg
email: yushuyi (at) uchicago.edu

# Search Engine Optimization (SEO)
keywords: shuyi yu, yu shuyi, shuyiyu, yushuyi

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
#link_type: icon #text/icon
#google_scholar: https://scholar.google.com/citations?user=Qi2PSmEAAAAJ
#github_link: https://github.com/yaoyao-liu/
#linkedin: https://www.linkedin.com/in/liuyaoyao/
#twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: https://shuyiyyu.github.io/avatar.jpg

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
